# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c56ffd6d08ec23469be2aafe6b26952f452bb1e17d76c58bad689bce8b9595275b0d5949038b3bd91636c7deb7b1c6d0c7f8f312fdf3bb96e16bc7d1505f25d5

test:
  secret_key_base: c54ef97986d1a46b516d91eebfa27fb6f54885d86708a621af1ff88c5924d83bc045bd116444c903b7369e9199a3b606aee365e3a2cf06ec922cdc7a10ac1116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
